### ISSUE TITLE
Automatic loading of GPR file

### ISSUE THREAD

**Issue by AlexandreMarkus** [AdaCore/ada_language_server#1050]
Right now, we need to manually add the .gpr file in the VS Code extension. It would be great if when loading a project, it would scan the folder to find the .gpr file.

**Comment by reznikmm** [comment]
Actually, the extension (the language server to be more precise) loads the project file if there is a single project file in the root folder. Other cases don't work because

 * if there are several project it's hard to choose one of them
 * initially we scanned for project files in sub-folders, but then we rejected this approach, because the file hierarchy could be huge and this slowdowns the extension greatly

So I'm closing this issue, but if you have ideas how to improve the behavior feel free to propose them.

**Comment by AlexandreMarkus** [comment]
Ohh I didn't know. My .gpr file is in a folder. I did try to add the following as a parameter: folderName/*.gpr so all my projects would be able to open since they all follow the same architecture but this doesn't work. Do you know if there is a way to achieve this?
