### ISSUE TITLE
[Bug]: error: expected type "Standard.Boolean" with lsp-gpr_files.adb

### ISSUE THREAD

**Issue by Blady-Com** [AdaCore/ada_language_server#1199]
### Environment

- OS and Version: macOS 13.6, Xcode 14.3, GNAT FSF 13.2 (from Alire)
- IDE Version: none
- Ada & SPARK Extension Version: none

### Bug Summary and Reproducer

Bug Summary:
Compilation error with lsp-gpr_files.adb.
Steps to reproduce:
Get ALS source from als-25.0w-20240506-162AE-src.
Launch make:
% make BUILD_MODE=prod
...
gprbuild -m -j4  -XSUPERPROJECT= -P gnat/lsp_server.gpr -p -XBUILD_MODE=prod -XOS=osx -XLIBRARY_TYPE=relocatable -XXMLADA_BUILD=relocatable -XGPR_BUILD=relocatable \
	-XVERSION= -XBUILD_DATE=
lsp_server.gpr:28:09: warning: there are no sources of language "C++" in this project
Compile
...
   [Ada]          lsp-gpr_files.adb
lsp-gpr_files.adb:1476:17: error: expected type "Standard.Boolean"
lsp-gpr_files.adb:1476:17: error: found private type "Ada.Containers.Doubly_Linked_Lists.List" from instance at gpr2-path_name-set.ads:11

Expected behavior:
How to fix it to get compilation correct?

### Configuration and Logs

```shell
none
```

**Comment by AnthonyLeonardoGracio** [comment]
Hello, 

It's strange the ALS builds fine here: https://github.com/AdaCore/ada_language_server/actions/runs/9654634380

Check with the latest sources, maybe the problem has been fixed since then. Note that we don't maintain the Mac OS compiler, so if it's a compiler issue, it should be reported to the maintainer.

Regards,
