### ISSUE TITLE
Intellisense reporting everything in scope

### ISSUE THREAD

**Issue by Entomy** [AdaCore/ada_language_server#234]
Rather than reporting what would be a valid completion for the given context, intellisense seems to be reporting everything known within the current scope, without any contextual discrimination.

![image](https://user-images.githubusercontent.com/25399505/68975734-0bb9d780-07c2-11ea-9304-5ce9ddda4855.png)

And no matter the leading context.

![image](https://user-images.githubusercontent.com/25399505/68975774-268c4c00-07c2-11ea-800c-baa118f5148e.png)

**Comment by raph-amiard** [comment]
Hi @Entomy, thanks for the report (s).

Indeed, code completion is very alpha for the moment. The implementation is a crude one and hasn't been refined yet, it is on our roadmap for the following releases.

The problem you're reporting is due to the fact (I think) that scopes will be explored recursively, without taking into account whether it should happen or not:

- When you're completing at the top level (no `A.B.[...]` context) the lookup should be recursive
- When you're completing after a dot, the lookup shouldn't be recursive.

#233 seems to be the same issue more or less. I'll investigate and see if we can make a quick fix.

**Comment by raph-amiard** [comment]
@Entomy I actually cannot reproduce this, do you think you could provide a reproducer? That would greatly speed up the investigations. Thanks in advance.

**Comment by Entomy** [comment]
I just installed the extension and loading up my [letscode-cards](https://github.com/Entomy/letscode-cards) repo so I had some code to test out. Then it was just a matter of trying things out. In certain places it seemed to work reasonably, but most places you get what I showed before. I couldn't determine any particular pattern to this. That's all I got.

**Comment by raph-amiard** [comment]
OK thanks @Entomy, I found one case where it happens, which is when I start insertion in the middle of an identifier, like this:

```
Ada.Text|
         ^ cursor here
```

in that case, the ada language server will fail to detect that it is completing in the context of a `DottedName`, and will complete everything.

Hopefully that's the case you're stumbling upon. I have a fix in the pipes, that I will push so you'll be able to tell me if it fixes it for you or not.

**Comment by Entomy** [comment]
These might have similar root causes since it's the same presentation, however in my case, as you can see in the screenshots I provided, this was happening immediately after the `.`, before the identifier.

**Comment by reznikmm** [comment]
I hope this is fixed too.
