### ISSUE TITLE
Integration with QtCreator

### ISSUE THREAD

**Issue by david-tamar** [AdaCore/ada_language_server#381]
Has anyone tried ALS on QtCreator's LSP client? I showed QtCreator where's `ada_language_server` but apparently nothing happens. Do I need to add .gpr files in order to make ALS work? I have a basic .adb file with a .pro file I made specifically for this tiny project.

**Comment by Entomy** [comment]
I didn't even know QtCreator added in an LSP client. Neat.

When you launch QtC from the terminal and attempt this, are there any logged messages, or nothing at all?

**Comment by david-tamar** [comment]
> I didn't even know QtCreator added in an LSP client. Neat.

Yep. LSP was introduced in version 4.8. Creator is quite amazing and snappy. I prefer Qt over Electron so I thought I should at least try, although I never used Creator before.

> When you launch QtC from the terminal and attempt this, are there any logged messages, or nothing at all?

I see these messages:
```
LanguageClient Ada: Initialize result is not valid: capabilities->codeActionProvider->Expected type Bool but value contained Object
LanguageClient Ada: InternalError: CONSTRAINT_ERROR
[/home/david/bin/ada_language_server]
0x83bfb5
0x84a29d
0x886f86
0x7dc3e6
0x7de92d
0x7ad2e3
0x7d4010
0x7d3045
[/home/david/bin/libgnarl-2019.so]
0x7f150b3733f4
[/lib/x86_64-linux-gnu/libpthread.so.0]
0x7f150ad92f25
[/lib/x86_64-linux-gnu/libc.so.6]
0x7f150aca32ad
0xfffffffffffffffe
```

This is Debian Sid with: Creator v4.11.0, GNAT v9.3.0,  gprbuild 2019, libc6 v2.30, GCC v9.3.0, v8.4.0, and v4:9.2.1, and the recent build-essentials from Debian. Am I missing anything? I don't have GPS installed.

**Comment by Entomy** [comment]
I've been having this happen a lot as well, with vs code. It's not a client issue, it's a server issue. I don't know enough about the internals to guess why. One of the AdaCore guys needs to get this one.

**Comment by Entomy** [comment]
@david-tamar would you try this again, as described in the new changes to the README?

**Comment by david-tamar** [comment]
@Entomy, I want to try it again; however, I'm not sure whether or not a .gpr file is needed for ALS to work properly. I also don't know how to generate .gpr files in the command line. I tried to approach the official AdaCore documentation on the GPR build system, but it's huge, and the Debian manpage is merely a short introduction. I've figured out how to generate a .cgpr file via `gprconfig`, but isn't that different from .gpr?
Can I use CMake with ALS instead? Are there any other GPR alternatives? QtCreator understands CMake, qmake, and Qbs, so I'm not even sure how's Creator going to interact with GPR if ALS needs it.

**Comment by Entomy** [comment]
> however, I'm not sure whether or not a .gpr file is needed for ALS to work properly.

![image](https://user-images.githubusercontent.com/25399505/78809752-60d6cf80-7995-11ea-8fbf-c0c53cd7ea9c.png)

As you can see, there's no GPR, so it's not required. 

>I've figured out how to generate a .cgpr file via gprconfig, but isn't that different from .gpr?

Yes, gpr config files are separate from gpr project files.

> Can I use CMake with ALS instead? Are there any other GPR alternatives?

Not sure about CMake, never used it for anything; never needed to. As for GPR alternatives, depending on your scenario, gnatmake may be enough. Seen quite a few people use GNU make. Otherwise, I have a proof-of-concept I will return to after some other work is done, but otherwise, no.

**Comment by reznikmm** [comment]
@david-tamar The simplest way is to put all your Ada files in the QtCreator project (root) directory. This way you don't need a GPR project file (ALS will create a trivial project file for you). This is how it works on the picture above in previous post.

But I recommend you to create a simple GPR like `default.gpr`:
```
project Default is
   for Source_Dirs use ("source");
   for Main use ("main.adb");  --  Optional
end Default;
```
* `source` - is directory with Ada files
* `main.adb` - a main file for your program if any

Using a GPR file you can build the project with `gprbuild`:
```
gprbuild -P default.gpr
```

If you really need an integration with `cmake` try to investigate [this](https://github.com/mosteo/ada4cmake). But ALS doesn't use/understand `cmake`.

I'm closing this issue, because it's fixed now. But don't hesitate to ask or comment.
