### ISSUE TITLE
Highlighting of nested declarations is failing

### ISSUE THREAD

**Issue by raph-amiard** [AdaCore/ada_language_server#412]
See attached screenshot

![failure](https://user-images.githubusercontent.com/478727/79872727-706b0500-83e6-11ea-9d6e-49a9fd69e0e8.png)

with this following snippet of code

```ada
with Ada.Text_IO;

procedure Main is
   package B is
      procedure C is
      begin
      end C;
   end B;

   procedure D is
   begin
   end D;
begin
end Main;
```

**Comment by AnthonyLeonardoGracio** [comment]
@Entomy I suppose that it's related to your recent syntax highlighting patches no?

**Comment by Entomy** [comment]
Yeah it would be. I can have a look at it tomorrow, as I'm busy for the rest of today.

**Comment by Entomy** [comment]
I checked the file over. `basic_declaration` should include `package_specification` before `subprogram_specification`.

If someone wants to do it before I can, that should do it.

**Comment by gcluzel** [comment]
Ok, I've corrected that as I'm doing some patches. Can someone tell me if a procedure body is allowed in a package spec? GCC rejects this program, and the Ada RM too.
```Ada
with Ada.Text_IO;

procedure Main is
   package B is
      procedure C is
      begin         -- here
      end C;        -- and here
   end B;

   procedure D is
   begin
   end D;
begin
end Main;
```

**Comment by raph-amiard** [comment]
> Ok, I've corrected that as I'm doing some patches. Can someone tell me if a procedure body is allowed in a package spec? GCC rejects this program, and the Ada RM too.

It's illegal indeed. The correct form would be:

```ada
with Ada.Text_IO;

procedure Main is
   package B is
      procedure C;
   end B;

   package body B is
      procedure C is
      begin
         null;
      end C;
   end B;
```

However, and I cannot emphasize that enough: *We don't want to highlight only correct programs*. In light of that, having such a rigid set of rules doesn't seem like a good idea, unless you can fallback on simple keyword highlighting in everycase.

**Comment by raph-amiard** [comment]
FWIW it also wildly fails on highlighting string literals:

![failure2](https://user-images.githubusercontent.com/478727/79959791-d4dca180-8484-11ea-9719-6ff9862a15bf.png)

**Comment by gcluzel** [comment]
What I have done so far is adding procedure calls and resolving bugs that I found in highlighting package body and so on.
![image](https://user-images.githubusercontent.com/34268335/79963845-318e8b00-848a-11ea-9589-a83486ebf4b6.png)
I think that it should do what you want.

**Comment by raph-amiard** [comment]
Thanks, it's looking good indeed :) I guess that the fact that quotes are
not highlighted similar as the rest of the string is voluntary then ?

**Comment by gcluzel** [comment]
@raph-amiard The quotes are marked as a punctuation character. It's voluntary, and it's what is done in other languages too. But asking @Entomy about that is probably the best.

**Comment by Entomy** [comment]
@raph-amiard is correct in that a classifier should not be handling exclusively valid syntax. It should handle _all_ syntax. A fallback mechanism is easily possible by adding the entire keyword list at the very end of the top level includes. I'm holding off on doing this because the moment you add this, it becomes very difficult to see which valid constructs aren't being highlighted. There are certain generalizations I've been making along the way to help with this, however. Ada has many different expression classifications for instance, with only some valid in certain contexts; they all use the same definition in the classifier and will always be highlighted even in a context where a different expression was expected.

**Comment by Entomy** [comment]
@gcluzel the quotes aren't marked as `punctuation.ada` but rather, it's own specific quote classification that other languages also use. You are very correct on that last part. @raph-amiard whether that is highlighted differently and how depends on the theme, not the classifier. Some themes highlight it the same, other themes differently. But that's a theming, not classification, decision.

**Comment by Entomy** [comment]
Since I have a computer I can take a screenshot on now, here's an example of a theme (the default dark theme Dark+), which uses the same styling for an entire string.

![image](https://user-images.githubusercontent.com/25399505/80011936-8df9a680-849a-11ea-84a3-931c85b40dad.png)

@gcluzel I owe you a bit of an apology. Haven't looked at the classification in so long I forgot it was a subclass of punctuation, `punctuation.definition.string.ada` specifically. I was thinking `*.quoted.double.*` but that's for the entire string itself, not the delimiters.

**Comment by raph-amiard** [comment]
@Entomy 

> A fallback mechanism is easily possible by adding the entire keyword list at the very end of the top level includes. I'm holding off on doing this because the moment you add this, it becomes very difficult to see which valid constructs aren't being highlighted. 

Ok I understand. I'll give this a whirl sometime soon, and report other similar issues that I find then. 

> whether that is highlighted differently and how depends on the theme, not the classifier. Some themes highlight it the same, other themes differently. But that's a theming, not classification, decision.

Ok!

**Comment by setton** [comment]
The engine is capable of giving a visual cue that a procedure body doesn't belong in a package spec:

![nesting](https://user-images.githubusercontent.com/96973/80524660-fa264f80-895d-11ea-894b-0cb559743478.png)

This is quite neat! Now we need to add support for "is null;" procedures and for expression functions.

In the meantime, closing this.
