### ISSUE TITLE
Completion of procedure calls

### ISSUE THREAD

**Issue by gcluzel** [AdaCore/ada_language_server#440]
When I use Intellisense to complete the name of a procedure in my code, all the arguments are added on the line. Maybe a screenshot can help to understand:
![image](https://user-images.githubusercontent.com/34268335/80956252-224ffb80-8e01-11ea-9527-650e43ec0314.png)
I think it would be better to only complete the name of the function without the parameters and open a help pop-up like it's done in other languages like Python as soon as the parenthesis is opened (screenshot below).
![image](https://user-images.githubusercontent.com/34268335/80956528-b4f09a80-8e01-11ea-9a24-c7cec4b16283.png)
I have no idea about the complexity of this request, but I find how it's done now isn't very usual to me, and I guess it's something that can be done to improve user-experience.

**Comment by raph-amiard** [comment]
Hello Guillaume,

The reason it is done this way is two-folds:

1. It is the supported way of doing parameter completion with the LSP, with specific requests provided for this use case. The way the python extension does it is *not* supported, and they very likely use VS Code specific APIs to show the pop up. Given our focus on doing as generic an engine as possible, especially where other IDEs than GNATStudio are concerned, this is probably a no-go for us.
2. Ada supports a very complex brand of subprogram overloading, where since the return type and the argument types can be overloaded, the exact function that is called depends on the whole context, not only what is inside the parens for the call to a function, but also the surrounding context. For those reasons, it is very hard to provide a general solution here, since the code being completed is 99% of the time incomplete and incorrect, knowing which overload the users want is generally impossible. While we could work something out, it would generally be more complex because it would have to "guess" which function you wanted to call, whereas the current mechanism doesn't have to, since it is the user that selects which overloads he wants to call.

For those reasons, while it was considered, it is very unlikely that we support this kind of parameter completion in the near future, especially in VS Code - even though we see the value.

Please keep us updated of how you accomodate to this way of doing parameter completion! we'll consider alternate schemes long run if this is not ideal.

**Comment by gcluzel** [comment]
Thank you @raph-amiard for your response. I asked without really documented myself of the internal mechanisms, then I didn't really know if it was feasible or not.

Could you at least consider to add a basic solution where Intellisense only completes the name of the procedure without its arguments?
It would especially be useful when I close a subprogram body, to not have a situation like the following one.
![image](https://user-images.githubusercontent.com/34268335/80970526-98f9f280-8e1b-11ea-9507-068ece7b0f31.png)

**Comment by AnthonyLeonardoGracio** [comment]
> It would especially be useful when I close a subprogram body, to not have a situation like the following one.
> ![image](https://user-images.githubusercontent.com/34268335/80970526-98f9f280-8e1b-11ea-9507-068ece7b0f31.png)

This clearly should not happen, I'll have a look on that. 

On the issue's original topic, note that language servers for languages that support function overloading like Ada (C++, Java) do the exact same thing (see the attached screenshot: it's with Microsoft Java's Extension pack).

<img width="682" alt="Capture d’écran 2020-05-04 à 15 36 47" src="https://user-images.githubusercontent.com/5286422/80971911-b8921a80-8e1d-11ea-8285-3e290c4ff2b9.png">

**Comment by gcluzel** [comment]
If it is what is done in Java, it's probably because it's the best solution!
Thank you everyone for your responses!

**Comment by AnthonyLeonardoGracio** [comment]
> If it is what is done in Java, it's probably because it's the best solution!
> Thank you everyone for your responses!

And thank you for bringing this topic ;) I will fix the bug on the end labels for now.
