### ISSUE TITLE
Support for alire

### ISSUE THREAD

**Issue by TamaMcGlinn** [AdaCore/ada_language_server#503]
It would be really useful if, when you initialize a project which has a `.alire` directory adjacent to it, alr were called to get the correct project path set up so that everything works as expected. If this were built into ada_language_server, it would no longer be necessary to have an alr plugin in GnatStudio, and it would automatically extend to other clients using ada_language_server.

**Comment by reznikmm** [comment]
Could you provide more details about expected workflow, what is `.alire` is and what information should `als` get from `alr`?

**Comment by Fabien-Chouteau** [comment]
@TamaMcGlinn integration with alire is indeed an interesting idea for the language server, here are my two cents:
 - Alire is still in development so it is a bit early to plan this kind of integration, for instance we are currently talking about a refactoring of the manifest format so the way you plan to detect if a project uses Alire may change in the short term.
 - Using `alr setenv` would be much a more safe way of doing this because we plan to keep this command available and the output should remain stable. `alr setenv` also defines external scenario variables to configure the projects.
 - We plan to have a `alr edit` command that would start your favorite IDE with the correct environment. So it would have the same effect as what you describe here.

**Comment by reznikmm** [comment]
Let's continue the discussion in #668
