### ISSUE TITLE
Version output for 'ada_language_server' and upgrade information

### ISSUE THREAD

**Issue by wiremoons** [AdaCore/ada_language_server#608]
Hi

Firstly - thank you for providing the Ada Language Server!

Two reasons for opening this issue:

1. Is it possible to check the version of the Ada Language Server (ALS) installed with the Visual Studio Code (VSC) Ada Language Support Extension?  The only command line flags (on the Linux version) I can see are `--help` or `--tracefile=`. There is no: `--version`?
2. I recently upgraded the default ALS version included with the VSC Language Support Extension and found a great improvement. Thanks for fixing the bugs :) I could not figure out what the `vlsx` file was, and there is no such file included with the VSC Marketplace extension (on Ubuntu at least) that I found.  I expect it is me missing the obvious!

Anyway - I wrote a article for my blog on how I upgraded which is here:
[https://www.wiremoons.com/development/ada/source_code/2021/02/07/Upgrading-Ada-Language-Server.html](https://www.wiremoons.com/development/ada/source_code/2021/02/07/Upgrading-Ada-Language-Server.html)

Thought it may be useful for others too that come across this issue in the future perhaps.

Also if you can re-use any of the content for your documentation - the source Markdown is on my GitHub repo here if you can cut and paste any of it: [https://raw.githubusercontent.com/wiremoons/wiremoons.github.io/master/_posts/2021-02-07-Upgrading-Ada-Language-Server.md](https://raw.githubusercontent.com/wiremoons/wiremoons.github.io/master/_posts/2021-02-07-Upgrading-Ada-Language-Server.md)

Simon

**Comment by reznikmm** [comment]
Hello @wiremoons,

Thank you for the issue and a good feedback. I'll add `--version` command line option.

The `.vsix` (not `L`, but `I`!) is a vscode extension file. You can install it
* from then command line

      code --install-extension <path_to.vsix>

* from vscode, using the "Install from VSIX" command in the Extensions view command drop-down,
* from the Command Palette by typing "Extensions: Install from VSIX" command in it.

See [more details here](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix).

On each commit we upload `.vsix` file together with ALS binaries to the Bintray, because `.vsix` installation is a bit simpler that the procedure described in your blog. But please note, that the latest commit builds could introduce bugs and all of them have the same version, currently `22.0.999`. We release a new version of the extension once (or two times per) month. If we found a bug in the release, we fix it and release a new version, so recommended way to update is to use the latest version from the marketplace.

If you have ideas how to improve our documentation, please send us a PR. We will very appreciate!

**Comment by wiremoons** [comment]
Thank you @reznikmm for taking the time to explain the correct upgrade process, and how the `.vsix` file is used. Much appreciated.

Simon
