### ISSUE TITLE
VS Code extension unable to find gnatls

### ISSUE THREAD

**Issue by Surobaki** [AdaCore/ada_language_server#865]
I'm running the v23.0.2 version of the extension and Code OSS 1.62.0. My OS is Manjaro Linux (x86_64).
I made sure that my GNAT Community binaries are located in path, and performing `echo $PATH` shows that the GNAT Studio binaries directory is also there (`/opt/gnatstudio/bin`). Performing `gnatls` in the Linux terminal produces expected output.

In Code, however, the Ada Language Server extension raises _"Could not locate exec gnatls"_, is there any other path variable I should be aware of?

Thank you.

**Comment by reznikmm** [comment]
@Surobaki Try to open a terminal in Code (`` Ctrl+` ``) and run `which gnatls` to see if Code has an access to GNAT toolchain. It could be `snap` or `flatpack` issue if you Manjaro uses it.

**Comment by Surobaki** [comment]
@reznikmm Code does run all the GNAT toolchain binaries that I included in path, yeah. I'm not sure how to see whether or not it's either of those causing it, I usually just install packages via the AUR.

**Comment by reznikmm** [comment]
Because this message you will get if no GNAT in the `PATH`, I would suggest you to double check:

* Close all Code instances
* Open Manjaro terminal and set `PATH`:

      export PATH=/opt/gnatstudio/bin:$PATH

* Start Code from this Terminal

Another this to try is to check environment variables in a running `ada_language_server` process.
* See process list with `ps axf|less` and find the PID of `ada_language_server` for a running Code.
* Grep `PATH` from `/proc`:

      tr '\0' '\n' < /proc/<PUT_PID_HERE>/environ |grep ^PATH****

**Comment by Surobaki** [comment]
Thank you, after checking the process' environment variables I saw that there's no GNAT in the path of the process. Running Code from a terminal which had the in-session export worked as well.
To not need to launch Code from the terminal every time I decided to symlink the necessary binaries from `/opt/gnatstudio/bin` to a PATH that already exists in Code (i.e. `/home/<username>/.local/bin`).
